#!/usr/bin/env bash
set -euo pipefail

# PGC v6 keeps the released Base policy immutable and warm-starts the validated
# V5 Goal Graph / Proposal / Verifier sidecars. The new language-to-target path
# can influence actions only through a selected current-frame visual value.
# Successful future frames and task-appearance prototypes are training-only.
export PGC_VERSION=6
if [[ -n "${PGC_CONTINUE_FROM_STEP:-}" ]]; then
  export PGC_WARM_START_V5="${PGC_WARM_START_V5:-false}"
else
  export PGC_WARM_START_V5="${PGC_WARM_START_V5:-true}"
fi
export PGC_LEARNING_RATE="${PGC_LEARNING_RATE:-1.0e-4}"
export PGC_RESIDUAL_REGULARIZATION_WEIGHT="${PGC_RESIDUAL_REGULARIZATION_WEIGHT:-0.01}"
export PGC_RESIDUAL_SMOOTHNESS_WEIGHT="${PGC_RESIDUAL_SMOOTHNESS_WEIGHT:-0.01}"
export PGC_ACTION_CHUNK_RESIDUAL_MAX_ABS="${PGC_ACTION_CHUNK_RESIDUAL_MAX_ABS:-2.0}"
export PGC_ROLLOUT_INFERENCE_STEPS="${PGC_ROLLOUT_INFERENCE_STEPS:-10}"
export PGC_ACTION_GRIPPER_WEIGHT="${PGC_ACTION_GRIPPER_WEIGHT:-2.0}"
export PGC_ADVANTAGE_TEMPERATURE="${PGC_ADVANTAGE_TEMPERATURE:-0.25}"
export PGC_ADVANTAGE_CLIP="${PGC_ADVANTAGE_CLIP:-4.0}"
export PGC_CANDIDATE_MAX_SATURATION_FRACTION="${PGC_CANDIDATE_MAX_SATURATION_FRACTION:-0.25}"
export PGC_CANDIDATE_MAX_DELTA_RMS="${PGC_CANDIDATE_MAX_DELTA_RMS:-2.0}"
export PGC_TRAIN_GATE_THRESHOLD="${PGC_TRAIN_GATE_THRESHOLD:-0.20}"
export PGC_VERIFIER_START_STEP="${PGC_VERIFIER_START_STEP:-1500}"
export PGC_VERIFIER_RAMP_STEPS="${PGC_VERIFIER_RAMP_STEPS:-500}"
export PGC_EXECUTION_PREFIX_STEPS="${PGC_EXECUTION_PREFIX_STEPS:-10}"
export PGC_SUFFIX_LOSS_WEIGHT="${PGC_SUFFIX_LOSS_WEIGHT:-0.10}"
export PGC_SAME_STATE_SOURCE_ZERO_WEIGHT="${PGC_SAME_STATE_SOURCE_ZERO_WEIGHT:-1.0}"
export PGC_GOAL_SEPARATION_WEIGHT="${PGC_GOAL_SEPARATION_WEIGHT:-0.25}"
export PGC_GOAL_SEPARATION_MARGIN="${PGC_GOAL_SEPARATION_MARGIN:-0.20}"
export PGC_RESIDUAL_SEPARATION_WEIGHT="${PGC_RESIDUAL_SEPARATION_WEIGHT:-0.25}"
export PGC_RESIDUAL_SEPARATION_MARGIN="${PGC_RESIDUAL_SEPARATION_MARGIN:-0.05}"
export PGC_VERIFIER_WRONG_LANGUAGE_WEIGHT="${PGC_VERIFIER_WRONG_LANGUAGE_WEIGHT:-0.50}"
export PGC_VERIFIER_BAD_CANDIDATE_WEIGHT="${PGC_VERIFIER_BAD_CANDIDATE_WEIGHT:-0.50}"

export PGC_TARGET_BINDING_INTERACTION_WEIGHT="${PGC_TARGET_BINDING_INTERACTION_WEIGHT:-1.0}"
export PGC_TARGET_BINDING_PROTOTYPE_WEIGHT="${PGC_TARGET_BINDING_PROTOTYPE_WEIGHT:-0.50}"
export PGC_TARGET_BINDING_SOURCE_WEIGHT="${PGC_TARGET_BINDING_SOURCE_WEIGHT:-0.50}"
export PGC_TARGET_BINDING_HARD_NEGATIVE_WEIGHT="${PGC_TARGET_BINDING_HARD_NEGATIVE_WEIGHT:-0.50}"
export PGC_TARGET_BINDING_SEPARATION_WEIGHT="${PGC_TARGET_BINDING_SEPARATION_WEIGHT:-0.25}"
export PGC_TARGET_BINDING_HARD_NEGATIVE_MARGIN="${PGC_TARGET_BINDING_HARD_NEGATIVE_MARGIN:-0.20}"
export PGC_TARGET_BINDING_SEPARATION_MARGIN="${PGC_TARGET_BINDING_SEPARATION_MARGIN:-0.15}"
export PGC_TARGET_BINDING_TEACHER_TOPK="${PGC_TARGET_BINDING_TEACHER_TOPK:-0.15}"
export PGC_TARGET_BINDING_TEACHER_TEMPERATURE="${PGC_TARGET_BINDING_TEACHER_TEMPERATURE:-0.25}"
export PGC_TARGET_BINDING_HIDDEN_DIM="${PGC_TARGET_BINDING_HIDDEN_DIM:-256}"
export PGC_TARGET_BINDING_NUM_HEADS="${PGC_TARGET_BINDING_NUM_HEADS:-8}"
export PGC_TARGET_BINDING_TEMPERATURE="${PGC_TARGET_BINDING_TEMPERATURE:-0.07}"
export PGC_TARGET_BINDING_PROTOTYPE_SLOTS="${PGC_TARGET_BINDING_PROTOTYPE_SLOTS:-64}"
export PGC_TARGET_BINDING_PROTOTYPE_MOMENTUM="${PGC_TARGET_BINDING_PROTOTYPE_MOMENTUM:-0.95}"
export PGC_TARGET_BINDING_PROTOTYPE_TEMPERATURE="${PGC_TARGET_BINDING_PROTOTYPE_TEMPERATURE:-0.07}"
export PGC_TARGET_BINDING_PROTOTYPE_TOPK="${PGC_TARGET_BINDING_PROTOTYPE_TOPK:-0.10}"
export PGC_TARGET_BINDING_ACTION_START_STEP="${PGC_TARGET_BINDING_ACTION_START_STEP:-1000}"
export PGC_TARGET_BINDING_ACTION_RAMP_STEPS="${PGC_TARGET_BINDING_ACTION_RAMP_STEPS:-500}"

if [[ -z "${PGC_INIT_CHECKPOINT:-}" ]]; then
  echo "Set PGC_INIT_CHECKPOINT to the validated suite-specific PGC v5 checkpoint." >&2
  exit 1
fi

exec bash scripts/train_pgc_libero_suite.sh "$@"
