#!/usr/bin/env bash
set -euo pipefail

# PGC v5 keeps the released Base Action Expert immutable and reuses the v4
# rollout-aligned final-action Proposal. It adds same-state paired-language
# supervision, aligns the main action objective/verifier to LIBERO's executed
# 10-step prefix, and trains the verifier with wrong-language and deliberately
# mirrored bad candidates.
export PGC_VERSION=5
export PGC_LEARNING_RATE="${PGC_LEARNING_RATE:-1.0e-4}"
export PGC_RESIDUAL_REGULARIZATION_WEIGHT="${PGC_RESIDUAL_REGULARIZATION_WEIGHT:-0.01}"
export PGC_RESIDUAL_SMOOTHNESS_WEIGHT="${PGC_RESIDUAL_SMOOTHNESS_WEIGHT:-0.01}"
export PGC_ACTION_CHUNK_RESIDUAL_MAX_ABS="${PGC_ACTION_CHUNK_RESIDUAL_MAX_ABS:-2.0}"
export PGC_ROLLOUT_INFERENCE_STEPS="${PGC_ROLLOUT_INFERENCE_STEPS:-10}"
export PGC_ACTION_GRIPPER_WEIGHT="${PGC_ACTION_GRIPPER_WEIGHT:-2.0}"
export PGC_ADVANTAGE_TEMPERATURE="${PGC_ADVANTAGE_TEMPERATURE:-0.25}"
export PGC_ADVANTAGE_CLIP="${PGC_ADVANTAGE_CLIP:-4.0}"
export PGC_CANDIDATE_MAX_SATURATION_FRACTION="${PGC_CANDIDATE_MAX_SATURATION_FRACTION:-0.25}"
export PGC_CANDIDATE_MAX_DELTA_RMS="${PGC_CANDIDATE_MAX_DELTA_RMS:-2.0}"
export PGC_TRAIN_GATE_THRESHOLD="${PGC_TRAIN_GATE_THRESHOLD:-0.20}"
export PGC_VERIFIER_START_STEP="${PGC_VERIFIER_START_STEP:-1000}"
export PGC_VERIFIER_RAMP_STEPS="${PGC_VERIFIER_RAMP_STEPS:-500}"
export PGC_EXECUTION_PREFIX_STEPS="${PGC_EXECUTION_PREFIX_STEPS:-10}"
export PGC_SUFFIX_LOSS_WEIGHT="${PGC_SUFFIX_LOSS_WEIGHT:-0.10}"
export PGC_SAME_STATE_SOURCE_ZERO_WEIGHT="${PGC_SAME_STATE_SOURCE_ZERO_WEIGHT:-1.0}"
export PGC_GOAL_SEPARATION_WEIGHT="${PGC_GOAL_SEPARATION_WEIGHT:-0.25}"
export PGC_GOAL_SEPARATION_MARGIN="${PGC_GOAL_SEPARATION_MARGIN:-0.20}"
export PGC_RESIDUAL_SEPARATION_WEIGHT="${PGC_RESIDUAL_SEPARATION_WEIGHT:-0.25}"
export PGC_RESIDUAL_SEPARATION_MARGIN="${PGC_RESIDUAL_SEPARATION_MARGIN:-0.05}"
export PGC_VERIFIER_WRONG_LANGUAGE_WEIGHT="${PGC_VERIFIER_WRONG_LANGUAGE_WEIGHT:-0.50}"
export PGC_VERIFIER_BAD_CANDIDATE_WEIGHT="${PGC_VERIFIER_BAD_CANDIDATE_WEIGHT:-0.50}"

exec bash scripts/train_pgc_libero_suite.sh "$@"
