#!/usr/bin/env bash
set -euo pipefail

# PGC v7 keeps the released Base, V5 Proposal, and hard gate protected while
# replacing V6's ambiguous future-change/prototype teachers with explicit
# current-frame robosuite element masks. Masks are training-only; deployment
# still consumes the same RGB observations and language as FastWAM.
export PGC_VERSION=7
if [[ -n "${PGC_CONTINUE_FROM_STEP:-}" ]]; then
  export PGC_WARM_START_V5="${PGC_WARM_START_V5:-false}"
else
  export PGC_WARM_START_V5="${PGC_WARM_START_V5:-true}"
fi
export PGC_LEARNING_RATE="${PGC_LEARNING_RATE:-1.0e-4}"
export PGC_ACTION_CHUNK_RESIDUAL_MAX_ABS="${PGC_ACTION_CHUNK_RESIDUAL_MAX_ABS:-2.0}"
export PGC_ROLLOUT_INFERENCE_STEPS="${PGC_ROLLOUT_INFERENCE_STEPS:-10}"
export PGC_ACTION_GRIPPER_WEIGHT="${PGC_ACTION_GRIPPER_WEIGHT:-2.0}"
export PGC_ADVANTAGE_TEMPERATURE="${PGC_ADVANTAGE_TEMPERATURE:-0.25}"
export PGC_ADVANTAGE_CLIP="${PGC_ADVANTAGE_CLIP:-4.0}"
export PGC_CANDIDATE_MAX_SATURATION_FRACTION="${PGC_CANDIDATE_MAX_SATURATION_FRACTION:-0.25}"
export PGC_CANDIDATE_MAX_DELTA_RMS="${PGC_CANDIDATE_MAX_DELTA_RMS:-2.0}"
export PGC_TRAIN_GATE_THRESHOLD="${PGC_TRAIN_GATE_THRESHOLD:-0.20}"
export PGC_VERIFIER_START_STEP="${PGC_VERIFIER_START_STEP:-1500}"
export PGC_VERIFIER_RAMP_STEPS="${PGC_VERIFIER_RAMP_STEPS:-500}"
export PGC_EXECUTION_PREFIX_STEPS="${PGC_EXECUTION_PREFIX_STEPS:-10}"
export PGC_SUFFIX_LOSS_WEIGHT="${PGC_SUFFIX_LOSS_WEIGHT:-0.10}"
export PGC_SAME_STATE_SOURCE_ZERO_WEIGHT="${PGC_SAME_STATE_SOURCE_ZERO_WEIGHT:-1.0}"
export PGC_GOAL_SEPARATION_WEIGHT="${PGC_GOAL_SEPARATION_WEIGHT:-0.25}"
export PGC_GOAL_SEPARATION_MARGIN="${PGC_GOAL_SEPARATION_MARGIN:-0.20}"
export PGC_RESIDUAL_SEPARATION_WEIGHT="${PGC_RESIDUAL_SEPARATION_WEIGHT:-0.25}"
export PGC_RESIDUAL_SEPARATION_MARGIN="${PGC_RESIDUAL_SEPARATION_MARGIN:-0.05}"
export PGC_VERIFIER_WRONG_LANGUAGE_WEIGHT="${PGC_VERIFIER_WRONG_LANGUAGE_WEIGHT:-0.50}"
export PGC_VERIFIER_BAD_CANDIDATE_WEIGHT="${PGC_VERIFIER_BAD_CANDIDATE_WEIGHT:-0.50}"

export PGC_TARGET_BINDING_HIDDEN_DIM="${PGC_TARGET_BINDING_HIDDEN_DIM:-256}"
export PGC_TARGET_BINDING_NUM_HEADS="${PGC_TARGET_BINDING_NUM_HEADS:-8}"
export PGC_TARGET_BINDING_TEMPERATURE="${PGC_TARGET_BINDING_TEMPERATURE:-0.07}"
export PGC_TARGET_BINDING_NUM_OBJECT_TOKENS="${PGC_TARGET_BINDING_NUM_OBJECT_TOKENS:-8}"
export PGC_TARGET_BINDING_CAMERA_COUNT="${PGC_TARGET_BINDING_CAMERA_COUNT:-2}"
export PGC_TARGET_BINDING_VISUAL_ASPECT_RATIO="${PGC_TARGET_BINDING_VISUAL_ASPECT_RATIO:-2.0}"
export PGC_TARGET_MASK_WEIGHT="${PGC_TARGET_MASK_WEIGHT:-1.0}"
export PGC_SOURCE_MASK_WEIGHT="${PGC_SOURCE_MASK_WEIGHT:-0.50}"
export PGC_AUX_MASK_WEIGHT="${PGC_AUX_MASK_WEIGHT:-0.50}"
export PGC_MASK_MASS_WEIGHT="${PGC_MASK_MASS_WEIGHT:-0.50}"
export PGC_CROSS_OBJECT_WEIGHT="${PGC_CROSS_OBJECT_WEIGHT:-0.50}"
export PGC_CROSS_OBJECT_MARGIN="${PGC_CROSS_OBJECT_MARGIN:-0.25}"
export PGC_TARGET_BINDING_ACTION_START_STEP="${PGC_TARGET_BINDING_ACTION_START_STEP:-1000}"
export PGC_TARGET_BINDING_ACTION_RAMP_STEPS="${PGC_TARGET_BINDING_ACTION_RAMP_STEPS:-500}"

if [[ -z "${PGC_INIT_CHECKPOINT:-}" ]]; then
  echo "Set PGC_INIT_CHECKPOINT to the validated suite-specific PGC v5 checkpoint." >&2
  exit 1
fi

exec bash scripts/train_pgc_libero_suite.sh "$@"
